name: publish

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  publish:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set TAG to branch name when not a tagged commit
        if: startsWith(github.ref, 'refs/heads/')
        run: echo TAG=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV

      - name: Get TAG
        if: startsWith(github.ref, 'refs/tags/')
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Get Repo Owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Release build
        uses: docker/build-push-action@v3
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64
          build-args: |
            Version=${{  env.TAG }}
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/cats:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/cats:${{ env.TAG }}
            ghcr.io/${{ env.REPO_OWNER }}/cats:latest
