name: publish

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  publish:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get Repo Name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build development image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/heads/')
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64
          build-args: |
            Version=dev
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}

      - name: Get TAG
        if: startsWith(github.ref, 'refs/tags/')
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Build release image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64
          build-args: |
            Version=${{ env.TAG }}
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}
            ghcr.io/${{ env.REPO_NAME }}:latest
